/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppListingsIndexRouteImport } from './routes/_app/listings.index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppListingsIdRouteImport } from './routes/_app/listings.$id'
import { Route as AppDashboardVendorBookingsRouteImport } from './routes/_app/dashboard/vendor-bookings'
import { Route as AppDashboardUsersRouteImport } from './routes/_app/dashboard/users'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app/dashboard/settings'
import { Route as AppDashboardListingsRouteImport } from './routes/_app/dashboard/listings'
import { Route as AppDashboardApprovalsRouteImport } from './routes/_app/dashboard/approvals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsIndexRoute = AppListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppListingsIdRoute = AppListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardVendorBookingsRoute =
  AppDashboardVendorBookingsRouteImport.update({
    id: '/vendor-bookings',
    path: '/vendor-bookings',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardUsersRoute = AppDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardListingsRoute = AppDashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardApprovalsRoute = AppDashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/gallery': typeof AppGalleryRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/dashboard/approvals': typeof AppDashboardApprovalsRoute
  '/dashboard/listings': typeof AppDashboardListingsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/users': typeof AppDashboardUsersRoute
  '/dashboard/vendor-bookings': typeof AppDashboardVendorBookingsRoute
  '/listings/$id': typeof AppListingsIdRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/listings/': typeof AppListingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/gallery': typeof AppGalleryRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/': typeof AppIndexRoute
  '/dashboard/approvals': typeof AppDashboardApprovalsRoute
  '/dashboard/listings': typeof AppDashboardListingsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/users': typeof AppDashboardUsersRoute
  '/dashboard/vendor-bookings': typeof AppDashboardVendorBookingsRoute
  '/listings/$id': typeof AppListingsIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/listings': typeof AppListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dashboard/approvals': typeof AppDashboardApprovalsRoute
  '/_app/dashboard/listings': typeof AppDashboardListingsRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/users': typeof AppDashboardUsersRoute
  '/_app/dashboard/vendor-bookings': typeof AppDashboardVendorBookingsRoute
  '/_app/listings/$id': typeof AppListingsIdRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/listings/': typeof AppListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/privacy'
    | '/terms'
    | '/dashboard/approvals'
    | '/dashboard/listings'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/vendor-bookings'
    | '/listings/$id'
    | '/dashboard/'
    | '/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/terms'
    | '/'
    | '/dashboard/approvals'
    | '/dashboard/listings'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/vendor-bookings'
    | '/listings/$id'
    | '/dashboard'
    | '/listings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/gallery'
    | '/_app/privacy'
    | '/_app/terms'
    | '/_app/'
    | '/_app/dashboard/approvals'
    | '/_app/dashboard/listings'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/users'
    | '/_app/dashboard/vendor-bookings'
    | '/_app/listings/$id'
    | '/_app/dashboard/'
    | '/_app/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/': {
      id: '/_app/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AppListingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/listings/$id': {
      id: '/_app/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AppListingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/vendor-bookings': {
      id: '/_app/dashboard/vendor-bookings'
      path: '/vendor-bookings'
      fullPath: '/dashboard/vendor-bookings'
      preLoaderRoute: typeof AppDashboardVendorBookingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/users': {
      id: '/_app/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AppDashboardUsersRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/listings': {
      id: '/_app/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof AppDashboardListingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/approvals': {
      id: '/_app/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof AppDashboardApprovalsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardApprovalsRoute: typeof AppDashboardApprovalsRoute
  AppDashboardListingsRoute: typeof AppDashboardListingsRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardUsersRoute: typeof AppDashboardUsersRoute
  AppDashboardVendorBookingsRoute: typeof AppDashboardVendorBookingsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardApprovalsRoute: AppDashboardApprovalsRoute,
  AppDashboardListingsRoute: AppDashboardListingsRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardUsersRoute: AppDashboardUsersRoute,
  AppDashboardVendorBookingsRoute: AppDashboardVendorBookingsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppGalleryRoute: typeof AppGalleryRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppListingsIdRoute: typeof AppListingsIdRoute
  AppListingsIndexRoute: typeof AppListingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppGalleryRoute: AppGalleryRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppListingsIdRoute: AppListingsIdRoute,
  AppListingsIndexRoute: AppListingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
